#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev 2>/dev/null || true
mkdir -p /dev/pts
mount -t devpts none /dev/pts

echo "nvr-custom" > /proc/sys/kernel/hostname

echo ""
echo "=============================="
echo " linux-chenxing on SSR621Q   "
echo " Boot (USB) successful!      "
echo "=============================="
echo ""

ifconfig eth0 up
udhcpc -i eth0

mkdir -p /tmp/dropbear
dropbear -R -r /tmp/dropbear/rsa_host_key -r /tmp/dropbear/ecdsa_host_key -p 22

exec /sbin/getty -L ttyS0 115200 vt100
