#!/usr/bin/env python3
"""Rasterise a monospace TTF into the bitmap font fb-splash draws with.

The OSD used to carry 42 hand-drawn 5x7 glyphs scaled up six times, which is
why it looked like duplo and could not render lowercase. This bakes a real
font in at its native size instead, so nothing is scaled and the whole of
printable ASCII is available.

Bold by default: the OSD is composited over moving video, where a heavier
stroke stays readable against a bright frame.

    tools/mkfont.py > src/font.h
"""
import sys

from PIL import Image, ImageDraw, ImageFont

CELL_W, CELL_H = 16, 32
FIRST, LAST = 32, 126

# Bitstream Vera (DejaVu) and SIL OFL (Noto) both permit redistributing a
# rasterisation. First one present wins.
CANDIDATES = [
    ("/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
     "DejaVu Sans Mono Bold, Bitstream Vera Fonts Copyright (c) 2003 Bitstream, Inc."),
    ("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
     "DejaVu Sans Mono, Bitstream Vera Fonts Copyright (c) 2003 Bitstream, Inc."),
    ("/usr/share/fonts/truetype/noto/NotoSansMono-Regular.ttf",
     "Noto Sans Mono, SIL Open Font License 1.1"),
]


def pick_font():
    for path, credit in CANDIDATES:
        try:
            open(path, "rb").close()
        except OSError:
            continue
        return path, credit
    sys.exit("mkfont: no candidate font found")


def best_size(path):
    """Largest pixel size whose advance and line box still fit the cell."""
    chosen = None
    for size in range(6, 64):
        font = ImageFont.truetype(path, size)
        ascent, descent = font.getmetrics()
        advance = font.getlength("M")
        if advance <= CELL_W and ascent + descent <= CELL_H:
            chosen = (size, font, ascent)
    if chosen is None:
        sys.exit("mkfont: no size fits the cell")
    return chosen


def glyph_rows(font, ascent, ch):
    img = Image.new("L", (CELL_W, CELL_H), 0)
    draw = ImageDraw.Draw(img)
    # Centre the advance in the cell; baseline from the font's own ascent, so
    # every glyph sits on the same line.
    x = (CELL_W - font.getlength(ch)) / 2
    draw.text((x, ascent), ch, font=font, fill=255, anchor="ls")

    rows = []
    for y in range(CELL_H):
        bits = 0
        for x in range(CELL_W):
            # Threshold at mid grey: the framebuffer is 1bpp per glyph pixel,
            # there is nothing to anti-alias into.
            if img.getpixel((x, y)) >= 128:
                bits |= 1 << (CELL_W - 1 - x)
        rows.append(bits)
    return rows


def main():
    path, credit = pick_font()
    size, font, ascent = best_size(path)

    out = sys.stdout
    out.write("/*\n")
    out.write(" * Generated by tools/mkfont.py -- do not edit.\n")
    out.write(" *\n")
    out.write(f" * {credit}\n")
    out.write(f" * Rasterised at {size}px into a {CELL_W}x{CELL_H} cell.\n")
    out.write(" */\n")
    out.write(f"#define FONT_W {CELL_W}\n")
    out.write(f"#define FONT_H {CELL_H}\n")
    out.write(f"#define FONT_FIRST {FIRST}\n")
    out.write(f"#define FONT_LAST {LAST}\n\n")
    out.write(f"static const unsigned short font_bits[{LAST - FIRST + 1}][{CELL_H}] = {{\n")
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        rows = glyph_rows(font, ascent, ch)
        label = "space" if ch == " " else ch
        out.write(f"    {{ /* {label} */\n        ")
        out.write(", ".join(f"0x{r:04x}" for r in rows[:16]))
        out.write(",\n        ")
        out.write(", ".join(f"0x{r:04x}" for r in rows[16:]))
        out.write("\n    },\n")
    out.write("};\n")


if __name__ == "__main__":
    main()
